package internal

import "github.com/coalaura/onda/types"

func init() {
	types.RegisterSignature(types.KindAACAudio, types.TypeADTS, 0, []byte{0xff, 0xf1})
	types.RegisterSignature(types.KindAACAudio, types.TypeADTS, 0, []byte{0xff, 0xf9})
	types.RegisterSignature(types.KindAmigaOctaMED, types.TypeNone, 0, []byte("MMD0"))
	types.RegisterSignature(types.KindAmigaOctaMED, types.TypeNone, 0, []byte("MMD1"))
	types.RegisterSignature(types.KindAmigaOctaMED, types.TypeNone, 0, []byte("MMD2"))
	types.RegisterSignature(types.KindAmigaOctaMED, types.TypeNone, 0, []byte("MMD3"))
	types.RegisterSignature(types.KindAMRAudio, types.TypeNone, 0, []byte("#!AMR\n"))
	types.RegisterSignature(types.KindAMRWBAudio, types.TypeNone, 0, []byte("#!AMR-WB\n"))
	types.RegisterSignature(types.KindAUAudio, types.TypeNone, 0, []byte(".snd"))
	types.RegisterSignature(types.KindCAFAudio, types.TypeNone, 0, []byte("caff"))
	types.RegisterSignature(types.KindCommodoreSID, types.TypeNone, 0, []byte("PSID"))
	types.RegisterSignature(types.KindCommodoreSID, types.TypeNone, 0, []byte("RSID"))
	types.RegisterSignature(types.KindDSFAudio, types.TypeNone, 0, []byte("DSD "))
	types.RegisterSignature(types.KindDTSAudio, types.TypeNone, 0, []byte{0x1f, 0xff, 0xe8, 0x00})
	types.RegisterSignature(types.KindDTSAudio, types.TypeNone, 0, []byte{0x7f, 0xfe, 0x80, 0x01})
	types.RegisterSignature(types.KindDTSAudio, types.TypeNone, 0, []byte{0xfe, 0x7f, 0x01, 0x80})
	types.RegisterSignature(types.KindDTSAudio, types.TypeNone, 0, []byte{0xff, 0x1f, 0x00, 0xe8})
	types.RegisterSignature(types.KindFastTracker2ExtendedInstrument, types.TypeNone, 0, []byte("Extended Instrument: "))
	types.RegisterSignature(types.KindFastTrackerModule, types.TypeNone, 0, []byte("Extended Module: "))
	types.RegisterSignature(types.KindFLACAudio, types.TypeNone, 0, []byte("fLaC"))
	types.RegisterSignature(types.KindFLStudioProject, types.TypeNone, 0, []byte("FLhd"))
	types.RegisterSignature(types.KindGameBoySound, types.TypeNone, 0, []byte("GBS "))
	types.RegisterSignature(types.KindIFFContainer, types.TypeNone, 0, []byte("FORM"))
	types.RegisterSignature(types.KindImpulseTrackerInstrument, types.TypeNone, 0, []byte("IMPI"))
	types.RegisterSignature(types.KindImpulseTrackerModule, types.TypeNone, 0, []byte("IMPM"))
	types.RegisterSignature(types.KindImpulseTrackerSample, types.TypeNone, 0, []byte("IMPS"))
	types.RegisterSignature(types.KindMIDISequence, types.TypeNone, 0, []byte("MThd"))
	types.RegisterSignature(types.KindMonkeysAudio, types.TypeNone, 0, []byte("MAC "))
	types.RegisterSignature(types.KindMPEGAudio, types.TypeMP3ID3Tagged, 0, []byte("ID3"))
	types.RegisterSignature(types.KindMusepackAudio, types.TypeStreamVersion7, 0, []byte("MP+"))
	types.RegisterSignature(types.KindMusepackAudio, types.TypeStreamVersion8, 0, []byte("MPCK"))
	types.RegisterSignature(types.KindNESSoundFormat, types.TypeNone, 0, []byte("NESM\x1a"))
	types.RegisterSignature(types.KindNISTSPHEREAudio, types.TypeNone, 0, []byte("NIST_1A"))
	types.RegisterSignature(types.KindOptimFROGAudio, types.TypeNone, 0, []byte("OFR "))
	types.RegisterSignature(types.KindPlaylistFile, types.TypeNone, 0, []byte("[playlist]"))
	types.RegisterSignature(types.KindRKAudio, types.TypeNone, 0, []byte("RKA "))
	types.RegisterSignature(types.KindScreamTrackerModule, types.TypeNone, 44, []byte("SCRM"))
	types.RegisterSignature(types.KindShortenAudio, types.TypeNone, 0, []byte("ajkg"))
	types.RegisterSignature(types.KindSNESSPC, types.TypeNone, 0, []byte("SNES-SPC700 Sound File Data"))
	types.RegisterSignature(types.KindSonyWave64Audio, types.TypeNone, 0, []byte("riff\x2e\x91\xcf\x11\xa5\xd6\x28\xdb\x04\xc1\x00\x00"))
	types.RegisterSignature(types.KindTAKAudio, types.TypeNone, 0, []byte("tBaK"))
	types.RegisterSignature(types.KindTTAAudio, types.TypeNone, 0, []byte("TTA1"))
	types.RegisterSignature(types.KindVideoGameMusic, types.TypeNone, 0, []byte("Vgm "))
	types.RegisterSignature(types.KindVOCAudio, types.TypeNone, 0, []byte("Creative Voice File\x1a"))
	types.RegisterSignature(types.KindWavPackAudio, types.TypeNone, 0, []byte("wvpk"))

	types.RegisterMaskedSignature(types.KindDSDIFFAudio, types.TypeNone, 0, []byte("FORM\x00\x00\x00\x00FRM8"), []byte{0xff, 0xff, 0xff, 0xff, 0, 0, 0, 0, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindIFFContainer, types.TypeAIFCAudio, 0, []byte("FORM\x00\x00\x00\x00AIFC"), []byte{0xff, 0xff, 0xff, 0xff, 0, 0, 0, 0, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindIFFContainer, types.TypeAIFFAudio, 0, []byte("FORM\x00\x00\x00\x00AIFF"), []byte{0xff, 0xff, 0xff, 0xff, 0, 0, 0, 0, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindRIFFContainer, types.TypeCDAAudio, 0, []byte("RIFF\x00\x00\x00\x00CDDA"), []byte{0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindRIFFContainer, types.TypeDownloadableSounds, 0, []byte("RIFF\x00\x00\x00\x00DLS "), []byte{0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindRIFFContainer, types.TypeQCPAudio, 0, []byte("RIFF\x00\x00\x00\x00QLCM"), []byte{0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindRIFFContainer, types.TypeSoundFont2, 0, []byte("RIFF\x00\x00\x00\x00sfbk"), []byte{0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindRIFFContainer, types.TypeWAVAudio, 0, []byte("RIFF\x00\x00\x00\x00WAVE"), []byte{0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff})
}
