package internal

import "github.com/coalaura/onda/types"

func init() {
	types.RegisterSignature(types.KindBCFData, types.TypeNone, 0, []byte("BCF\x02"))
	types.RegisterSignature(types.KindBerkeleyDB, types.TypeNone, 0, []byte{0x00, 0x04, 0x09, 0x88})
	types.RegisterSignature(types.KindBerkeleyDB, types.TypeNone, 0, []byte{0x00, 0x04, 0x22, 0x53})
	types.RegisterSignature(types.KindBerkeleyDB, types.TypeNone, 0, []byte{0x00, 0x05, 0x31, 0x62})
	types.RegisterSignature(types.KindBerkeleyDB, types.TypeNone, 0, []byte{0x00, 0x06, 0x15, 0x61})
	types.RegisterSignature(types.KindFeatherData, types.TypeNone, 0, []byte("FEA1"))
	types.RegisterSignature(types.KindFITActivity, types.TypeNone, 8, []byte(".FIT"))
	types.RegisterSignature(types.KindGDBMDatabase, types.TypeNone, 0, []byte{0x13, 0x57, 0x9a, 0xcd})
	types.RegisterSignature(types.KindGDBMDatabase, types.TypeNone, 0, []byte{0x13, 0x57, 0x9a, 0xce})
	types.RegisterSignature(types.KindGDBMDatabase, types.TypeNone, 0, []byte{0x13, 0x57, 0x9a, 0xcf})
	types.RegisterSignature(types.KindGDBMDatabase, types.TypeNone, 0, []byte{0xcd, 0x9a, 0x57, 0x13})
	types.RegisterSignature(types.KindGDBMDatabase, types.TypeNone, 0, []byte{0xce, 0x9a, 0x57, 0x13})
	types.RegisterSignature(types.KindGDBMDatabase, types.TypeNone, 0, []byte{0xcf, 0x9a, 0x57, 0x13})
	types.RegisterSignature(types.KindGHCiInterface, types.Type32Bit, 0, []byte{0x1d, 0xfa, 0xce, 0x10})
	types.RegisterSignature(types.KindGHCiInterface, types.Type64Bit, 0, []byte{0x1d, 0xfa, 0xce, 0x14})
	types.RegisterSignature(types.KindGNUGettextMachineCatalog, types.TypeNone, 0, []byte{0x95, 0x04, 0x12, 0xde})
	types.RegisterSignature(types.KindGNUGettextMachineCatalog, types.TypeNone, 0, []byte{0xde, 0x12, 0x04, 0x95})
	types.RegisterSignature(types.KindHDF4Data, types.TypeNone, 0, []byte{0x0e, 0x03, 0x13, 0x01})
	types.RegisterSignature(types.KindKyotoCabinetDatabase, types.TypeNone, 0, []byte("KCDB"))
	types.RegisterSignature(types.KindLevelDB, types.TypeNone, 0, []byte{0x57, 0xfb, 0x80, 0x8b, 0x24, 0x75, 0x47, 0xdb})
	types.RegisterSignature(types.KindMATLABData, types.TypeNone, 0, []byte("MATLAB 5.0 MAT-file"))
	types.RegisterSignature(types.KindMicrosoftSQLServerDatabase, types.TypeNone, 0, []byte{0x01, 0x0f, 0x00, 0x00, 0x08, 0x02, 0x00, 0x00})
	types.RegisterSignature(types.KindNumPyArray, types.TypeNone, 0, []byte("\x93NUMPY"))
	types.RegisterSignature(types.KindOCamlObject, types.TypeNone, 0, []byte("Caml1999O"))
	types.RegisterSignature(types.KindPythonPickle, types.TypeNone, 0, []byte{0x80, 0x03})
	types.RegisterSignature(types.KindPythonPickle, types.TypeNone, 0, []byte{0x80, 0x04})
	types.RegisterSignature(types.KindPythonPickle, types.TypeNone, 0, []byte{0x80, 0x05})
	types.RegisterSignature(types.KindQDBMDatabase, types.TypeNone, 0, []byte("[QDBM]"))
	types.RegisterSignature(types.KindRData, types.TypeNone, 0, []byte("RDX2\n"))
	types.RegisterSignature(types.KindRData, types.TypeNone, 0, []byte("RDX3\n"))
	types.RegisterSignature(types.KindROOTData, types.TypeNone, 0, []byte("root"))
	types.RegisterSignature(types.KindRubyMarshal, types.TypeNone, 0, []byte{0x04, 0x08})
	types.RegisterSignature(types.KindSASData, types.TypeNone, 12, []byte{0xc2, 0xea, 0x81, 0x60, 0xb3, 0x14, 0x11, 0xcf, 0xbd, 0x92, 0x08, 0x00, 0x09, 0xc7, 0x31, 0x8c, 0x18, 0x1f, 0x10, 0x11})
	types.RegisterSignature(types.KindSPSSData, types.TypeNone, 0, []byte("$FL2"))
	types.RegisterSignature(types.KindSPSSPortableData, types.TypeNone, 0, []byte("SPSSPORT"))
	types.RegisterSignature(types.KindStataData, types.TypeNone, 0, []byte("<stata_dta>"))
	types.RegisterSignature(types.KindTensorFlowLiteModel, types.TypeNone, 4, []byte("TFL3"))
	types.RegisterSignature(types.KindTokyoCabinetDatabase, types.TypeNone, 0, []byte("ToCa"))
	types.RegisterSignature(types.KindXilinxBitstream, types.TypeNone, 0, []byte{0x00, 0x09, 0x0f, 0xf0, 0x0f, 0xf0, 0x0f, 0xf0, 0x0f, 0xf0, 0x00, 0x00, 0x01, 0x61})
}
