//go:build ignore

package internal

import "github.com/coalaura/onda/types"

func init() {
	types.RegisterSignature(types.KindAdobeInDesignDocument, types.TypeNone, 0, []byte{0x06, 0x06, 0xed, 0xf5, 0xd8, 0x1d, 0x46, 0xe5, 0xbd, 0x31, 0xef, 0xe7, 0xfe, 0x74, 0xb7, 0x1d})
	types.RegisterSignature(types.KindApacheArrowFile, types.TypeNone, 0, []byte("ARROW1"))
	types.RegisterSignature(types.KindApacheParquet, types.TypeNone, 0, []byte("PAR1"))
	types.RegisterSignature(types.KindAppleBinaryPropertyList, types.TypeNone, 0, []byte("bplist00"))
	types.RegisterSignature(types.KindAppleDesktopServicesStore, types.TypeNone, 0, []byte{0x00, 0x00, 0x00, 0x01, 'B', 'u', 'd', '1'})
	types.RegisterSignature(types.KindAutoCADDrawing, types.TypeNone, 0, []byte("AC10"))
	types.RegisterSignature(types.KindAvroObjectContainer, types.TypeNone, 0, []byte{'O', 'b', 'j', 0x01})
	types.RegisterSignature(types.KindBAMData, types.TypeNone, 0, []byte{'B', 'A', 'M', 0x01})
	types.RegisterSignature(types.KindCBORData, types.TypeNone, 0, []byte{0xd9, 0xd9, 0xf7})
	types.RegisterSignature(types.KindCHMDocument, types.TypeNone, 0, []byte("ITSF"))
	types.RegisterSignature(types.KindCRAMData, types.TypeNone, 0, []byte("CRAM"))
	types.RegisterSignature(types.KindDICOMMedicalImage, types.TypeNone, 128, []byte("DICM"))
	types.RegisterSignature(types.KindESRIShapefile, types.TypeNone, 0, []byte{0x00, 0x00, 0x27, 0x0a})
	types.RegisterSignature(types.KindFBXModel, types.TypeNone, 0, []byte("Kaydara FBX Binary  \x00"))
	types.RegisterSignature(types.KindFITSAstronomicalImage, types.TypeNone, 0, []byte("SIMPLE  ="))
	types.RegisterSignature(types.KindGRIBData, types.TypeNone, 0, []byte("GRIB"))
	types.RegisterSignature(types.KindHDF5Data, types.TypeNone, 0, []byte{0x89, 'H', 'D', 'F', 0x0d, 0x0a, 0x1a, 0x0a})
	types.RegisterSignature(types.KindICalendar, types.TypeNone, 0, []byte("BEGIN:VCALENDAR"))
	types.RegisterSignature(types.KindKeePassDatabase, types.TypeKDBX, 0, []byte{0x03, 0xd9, 0xa2, 0x9a, 0x67, 0xfb, 0x4b, 0xb5})
	types.RegisterSignature(types.KindMayaASCII, types.TypeNone, 0, []byte("//Maya"))
	types.RegisterSignature(types.KindMayaBinary, types.TypeNone, 0, []byte("FOR4"))
	types.RegisterSignature(types.KindMicrosoftAccessDatabase, types.TypeNone, 0, []byte{0x00, 0x01, 0x00, 0x00, 'S', 't', 'a', 'n', 'd', 'a', 'r', 'd', ' ', 'J', 'e', 't', ' ', 'D', 'B'})
	types.RegisterSignature(types.KindMicrosoftOutlookEmailFolder, types.TypeNone, 0, []byte("!BDN"))
	types.RegisterSignature(types.KindMOBIDocument, types.TypeNone, 60, []byte("BOOKMOBI"))
	types.RegisterSignature(types.KindNetCDFData, types.TypeNone, 0, []byte{'C', 'D', 'F', 0x01})
	types.RegisterSignature(types.KindNetCDFData, types.TypeNone, 0, []byte{'C', 'D', 'F', 0x02})
	types.RegisterSignature(types.KindORCColumnarData, types.TypeNone, 0, []byte("ORC"))
	types.RegisterSignature(types.KindPDFDocument, types.TypeNone, 0, []byte("%PDF-"))
	types.RegisterSignature(types.KindPGPMessage, types.TypeNone, 0, []byte("-----BEGIN PGP"))
	types.RegisterSignature(types.KindPLYModel, types.TypeNone, 0, []byte("ply\n"))
	types.RegisterSignature(types.KindPostgreSQLCustomDump, types.TypeNone, 0, []byte("PGDMP"))
	types.RegisterSignature(types.KindPostScriptDocument, types.TypeNone, 0, []byte("%!PS-Adobe-"))
	types.RegisterSignature(types.KindRedisDatabase, types.TypeNone, 0, []byte("REDIS"))
	types.RegisterSignature(types.KindRichTextFormatDocument, types.TypeNone, 0, []byte("{\\rtf"))
	types.RegisterSignature(types.KindSketchUpModel, types.TypeNone, 0, []byte("SketchUp Model"))
	types.RegisterSignature(types.KindSketchUpModel, types.TypeNone, 0, []byte{0xff, 0xfe, 0xff, 0x0e})
	types.RegisterSignature(types.KindSQLiteDatabase, types.TypeNone, 0, []byte("SQLite format 3\x00"))
	types.RegisterSignature(types.KindTimezoneData, types.TypeNone, 0, []byte("TZif"))
	types.RegisterSignature(types.KindU3DModel, types.TypeNone, 0, []byte("U3D\x00"))
	types.RegisterSignature(types.KindVCard, types.TypeNone, 0, []byte("BEGIN:VCARD"))
	types.RegisterSignature(types.KindWARCFile, types.TypeNone, 0, []byte("WARC/"))
	types.RegisterSignature(types.KindWebVTT, types.TypeNone, 0, []byte("WEBVTT"))
	types.RegisterSignature(types.KindWindowsRegistryHive, types.TypeNone, 0, []byte("regf"))
	types.RegisterSignature(types.KindXMLDocument, types.TypeNone, 0, []byte("<?xml"))

	types.RegisterMaskedSignature(types.KindHTMLDocument, types.TypeNone, 0, []byte("<!DOCTYPE HTML"), []byte{0xff, 0xff, 0xdf, 0xdf, 0xdf, 0xdf, 0xdf, 0xdf, 0xdf, 0xff, 0xdf, 0xdf, 0xdf, 0xdf})
	types.RegisterMaskedSignature(types.KindHTMLDocument, types.TypeNone, 0, []byte("<HTML "), []byte{0xff, 0xdf, 0xdf, 0xdf, 0xdf, 0xff})
	types.RegisterMaskedSignature(types.KindHTMLDocument, types.TypeNone, 0, []byte("<HTML>"), []byte{0xff, 0xdf, 0xdf, 0xdf, 0xdf, 0xff})
	types.RegisterMaskedSignature(types.KindRIFFContainer, types.TypeCorelDRAWDocumentCDR, 0, []byte("RIFF\x00\x00\x00\x00CDR\x00"), []byte{0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0x00})
}
