package internal

import "github.com/coalaura/onda/types"

func init() {
	types.RegisterSignature(types.KindAmigaDiskFile, types.TypeNone, 0, []byte("DOS\x00"))
	types.RegisterSignature(types.KindAmigaDiskFile, types.TypeNone, 0, []byte("DOS\x01"))
	types.RegisterSignature(types.KindAmigaDiskFile, types.TypeNone, 0, []byte("DOS\x02"))
	types.RegisterSignature(types.KindAmigaDiskFile, types.TypeNone, 0, []byte("DOS\x03"))
	types.RegisterSignature(types.KindAmigaHardDiskFile, types.TypeNone, 0, []byte("RDSK"))
	types.RegisterSignature(types.KindAtari7800ROM, types.TypeNone, 1, []byte("ATARI7800"))
	types.RegisterSignature(types.KindAtariLynxROM, types.TypeNone, 0, []byte("LYNX"))
	types.RegisterSignature(types.KindCloneCDControl, types.TypeNone, 0, []byte("[CloneCD]"))
	types.RegisterSignature(types.KindCommodore64Tape, types.TypeNone, 0, []byte("C64 tape image file"))
	types.RegisterSignature(types.KindCommodore64TapeRAW, types.TypeNone, 0, []byte("C64-TAPE-RAW"))
	types.RegisterSignature(types.KindCompressedSquareWave, types.TypeNone, 0, []byte("Compressed Square Wave"))
	types.RegisterSignature(types.KindDolphinRVZ, types.TypeNone, 0, []byte("RVZ\x01"))
	types.RegisterSignature(types.KindFamicomDiskSystemROM, types.TypeNone, 0, []byte("FDS\x1a"))
	types.RegisterSignature(types.KindGodotPackage, types.TypeNone, 0, []byte("GDPC"))
	types.RegisterSignature(types.KindMAMECHD, types.TypeNone, 0, []byte("MComprHD"))
	types.RegisterSignature(types.KindMUGENSound, types.TypeNone, 0, []byte("ElecbyteSnd\x00"))
	types.RegisterSignature(types.KindMUGENSprite, types.TypeNone, 0, []byte("ElecbyteSpr\x00"))
	types.RegisterSignature(types.KindNeoGeoPocketROM, types.TypeNone, 34, []byte("LICENSED BY SNK CORPORATION"))
	types.RegisterSignature(types.KindNintendoBCFNT, types.TypeNone, 0, []byte("CFFN"))
	types.RegisterSignature(types.KindNintendoBFLYT, types.TypeNone, 0, []byte("FLYT"))
	types.RegisterSignature(types.KindNintendoBRRES, types.TypeNone, 0, []byte("bres"))
	types.RegisterSignature(types.KindNintendoRARC, types.TypeNone, 0, []byte("RARC"))
	types.RegisterSignature(types.KindNintendoSwitchNRO, types.TypeNone, 16, []byte("NRO0"))
	types.RegisterSignature(types.KindNintendoSwitchNSO, types.TypeNone, 0, []byte("NSO0"))
	types.RegisterSignature(types.KindNintendoU8Archive, types.TypeNone, 0, []byte{0x55, 0xaa, 0x38, 0x2d})
	types.RegisterSignature(types.KindNintendoYay0, types.TypeNone, 0, []byte("Yay0"))
	types.RegisterSignature(types.KindNintendoYaz0, types.TypeNone, 0, []byte("Yaz0"))
	types.RegisterSignature(types.KindPlayStationExecutable, types.TypeNone, 0, []byte("SCE\x00"))
	types.RegisterSignature(types.KindPlayStationPortableExecutable, types.TypeNone, 0, []byte("\x00PBP"))
	types.RegisterSignature(types.KindQuakePAK, types.TypeNone, 0, []byte("PACK"))
	types.RegisterSignature(types.KindRenPyArchive, types.TypeNone, 0, []byte("RPA-3.0 "))
	types.RegisterSignature(types.KindRPGMakerArchive, types.TypeNone, 0, []byte("RGSSAD\x00"))
	types.RegisterSignature(types.KindSegaDreamcastROM, types.TypeNone, 16, []byte("SEGA SEGAKATANA"))
	types.RegisterSignature(types.KindSegaMasterSystemROM, types.TypeNone, 0x1FF0, []byte("TMR SEGA"))
	types.RegisterSignature(types.KindSegaMasterSystemROM, types.TypeNone, 0x3FF0, []byte("TMR SEGA"))
	types.RegisterSignature(types.KindSegaMasterSystemROM, types.TypeNone, 0x7FF0, []byte("TMR SEGA"))
	types.RegisterSignature(types.KindSegaSaturnROM, types.TypeNone, 0, []byte("SEGA SEGA"))
	types.RegisterSignature(types.KindSourceEngineBSP, types.TypeNone, 0, []byte("VBSP"))
	types.RegisterSignature(types.KindUnityWebData, types.TypeNone, 0, []byte("UnityFS"))
	types.RegisterSignature(types.KindUnityWebData, types.TypeNone, 0, []byte("UnityRaw"))
	types.RegisterSignature(types.KindUnityWebData, types.TypeNone, 0, []byte("UnityWeb"))
	types.RegisterSignature(types.KindUnrealEnginePackage, types.TypeNone, 0, []byte{0xc1, 0x83, 0x2a, 0x9e})
	types.RegisterSignature(types.KindValvePak, types.TypeNone, 0, []byte{0x34, 0x12, 0xaa, 0x55})
	types.RegisterSignature(types.KindWiiUArchive, types.TypeNone, 0, []byte("WUA\x01"))
	types.RegisterSignature(types.KindXbox360Executable, types.TypeNone, 0, []byte("XEX2"))
	types.RegisterSignature(types.KindXboxExecutable, types.TypeNone, 0, []byte("XBEH"))
}
